In [1]:
import pandas as pd
df = pd.read_csv("apy.csv")

In [2]:
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0
...,...,...,...,...,...,...,...
246086,West Bengal,PURULIA,2014,Summer,Rice,306.0,801.0
246087,West Bengal,PURULIA,2014,Summer,Sesamum,627.0,463.0
246088,West Bengal,PURULIA,2014,Whole Year,Sugarcane,324.0,16250.0
246089,West Bengal,PURULIA,2014,Winter,Rice,279151.0,597899.0
246090,West Bengal,PURULIA,2014,Winter,Sesamum,175.0,88.0

In [ ]:
# droping data before 2001
df = df.drop(df[df["Crop_Year"]<2001].index)

In [7]:
# droping data after 2010
df = df.drop(df[df["Crop_Year"]>2010].index)

In [8]:
# droping data for very low production state
df = df.drop(df[df["Production"] =="Andaman and Nicobar Islands"].index)

In [9]:
# droping data for small scale prodution
df=df.drop(df[df['Production']<=100].index)

In [10]:
df

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
10,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,Arecanut,1254.0,2061.00
12,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,Rice,83.0,300.00
13,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Cashewnut,719.0,192.00
14,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Coconut,18190.0,64430000.00
18,Andaman and Nicobar Islands,NICOBARS,2002,Kharif,Rice,189.2,510.84
...,...,...,...,...,...,...,...
245949,West Bengal,PURULIA,2010,Rabi,Wheat,2013.0,5152.00
245951,West Bengal,PURULIA,2010,Summer,Maize,258.0,391.00
245952,West Bengal,PURULIA,2010,Summer,Rice,105.0,281.00
245953,West Bengal,PURULIA,2010,Whole Year,Sugarcane,303.0,11541.00
245954,West Bengal,PURULIA,2010,Winter,Rice,152676.0,261435.00

In [11]:
# find out the total District Name
a=len(df["District_Name"].unique())
a

619

# saving updated data

In [12]:
df.to_csv("updated_crop.csv",index=False)